# Generated by Django 5.2.7 on 2025-10-31 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_remove_complaint_kseb_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='websitefeedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolutions/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='websitefeedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='websitefeedback',
            name='feedback',
            field=models.TextField(),
        ),
    ]
