# Generated by Django 5.2.7 on 2025-11-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaintreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
