# Generated by Django 5.2.7 on 2025-11-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_rated_at_complaint_user_rating_and_more'),
    ]

    operations = [
    ]
