# Generated by Django 5.2.7 on 2025-12-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_auto_20251108_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintreply',
            name='viewed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
